### ISSUE TITLE
wired stats don't work in unifi 5.5

### ISSUE THREAD

**Issue by akramer** [mdlayher/unifi#5]
They now seem to be called "wan" and "lan" and only exist for USGs. The "uplink" prefix seems to be gone.

**Comment by akramer** [comment]
I take it back: there now seems to be an entire "uplink" section, rather than just a prefix in the "stats" section.

**Comment by mdlayher** [comment]
Heh, this is exactly why relying on undocumented APIs is problematic.  I'm afraid that unless Ubiquiti is willing to stabilize it or provide _some_ supported mechanism for fetching information from a controller, we will forever face an uphill battle.

I'd accept a patch, but it's probably time to add a disclaimer that this package and the exporter will only ever attempt to work with the latest stable version of the UniFi controller.

**Comment by akramer** [comment]
Yeah, tracking poorly-supported-but-changing APIs is really frustrating. I wasn't opening this issue with the expectation that you'd fix it - I was opening it so I could attach a pull request later. :)

I am running the latest version of unifi on a Cloud Key, I think this is also broken for anyone who was monitoring uplink stats for APs or USGs on the stable version.

**Comment by mdlayher** [comment]
Yep, makes sense. Thanks in advance.

**Comment by akramer** [comment]
https://github.com/mdlayher/unifi/pull/6 should fix this.

**Comment by mdlayher** [comment]
Merged!
