### ISSUE TITLE
Unifi 5.7.20 Support

### ISSUE THREAD

**Issue by nickvanw** [mdlayher/unifi#7]
Hey @mdlayher! I'm not sure if you heard, but it looks like 5.7.20 has been fully released as stable: https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-5-7-20-Release-Update/ba-p/2278500

I upgraded on a whim today and it looks like there are a few changes in the API responses in places - at least enough that I noticed `unifi_exporter` wasn't collecting some stats.

If you haven't updated already, I wouldn't advise updating quite yet - if we all run the new version, there's nobody around to save API responses for 5.6.xx so that we can make sure it's as backwards compatible as possible (if that's a goal of yours).

Either way, I'll probably be taking a look at this over the next few days as I get it working on my local network, and look to see if I can find any other obvious places that it's not working. I don't expect you to do any work right now, but I wanted to flag this for you so you knew not to update, and so you'd know to expect a PR sometime this week hopefully. 

Let me know if that works for you and if you'd be open to accepting PRs for it!

**Comment by nickvanw** [comment]
It looks like the big noticeable change inside of `devices.go` is that there's no longer just stats for `na` and `ng`, but they are labeled per device `wlan0`, `wlan1`... on my AC-AP-LR. I suspect with additional APs have more radios, hence the change. Looking at some other client libraries, it looks like it might be straightforward to match devices across `radio_table` -> `radio_table_stats`. I'll have a branch up with that tomorrow probably, and you can test it on your network at some point to see if all of the data is present in 5.6.xx as well.

**Comment by mdlayher** [comment]
Sounds good. PRs definitely appreciated. I've kind of neglected my UniFi stuff because they keep changing the APIs.

**Comment by someone1** [comment]
I just noticed a few of my prometheus metrics started breaking too in March with the 5.7 update - is the PR good to merge or do you need additional testing/review?

**Comment by mdlayher** [comment]
Merged.  I'm not supporting this or unifi exporter, but if it helps some folks out, great!
